# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

res = 0
prv, cur = 1, 2

while cur < 4000000:
    if cur % 2 == 0:
        res += cur
    prv, cur = cur, prv + cur

print(res)  # 4613732

# Congratulations, the answer you gave to problem 2 is correct.

# You are the 646144th person to have solved this problem.

# This problem had a difficulty rating of 5%. The highest difficulty rating you have solved remains at 5%.